### PR TITLE
Increase CCE timeouts

### PR DESCRIPTION
**Pull request by outcatcher**

### CODE REVIEW

**Review by lego963 — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by outcatcher** [comment]
regate

**Review by lego963 — APPROVED** [review]

**Comment by gtema** [comment]
regate with increased global job timeout

**Comment by gtema** [comment]
regate

**Comment by gtema** [comment]
general timeout for any job in OTC is now set to 1h. This can be changed on the job level by setting timeout property (https://github.com/opentelekomcloud-infra/otc-zuul-jobs/blob/master/zuul.d/jobs.yaml#L15).
30 minutes here seems still not enough for CCE to properly complete (currently a clear cut after 30 min is visible)

**Comment by gtema** [comment]
it might be also helpful (if possible) to see some interim logs from tests, otherwise looks like it is being stuck.

**Comment by outcatcher** [comment]
@gtema I was expecting `-parallel=2` to help in this case. But it seems that CCE test alone can take more that 30 min. Cluster destruction can take really a lot of time.

**Review by lego963 — APPROVED** [review]

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Review by lego963 — APPROVED** [review]

**Review by lego963 — APPROVED** [review]

**Review by lego963 — APPROVED** [review]

**Pull request merged**
